package com.arka.model.eventstore;

/**
 * Marker class generated by Scaffold — actual domain records are EventStoreEntry and EventEnvelope.
 */
public final class EventStore {
    private EventStore() {}
}

