# Perfil DOCKER — cuando corre dentro de Docker Compose
spring:
  mongodb:
    uri: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@arka-mongodb:27017/db_cart?authSource=admin&replicaSet=rs0"

grpc:
  client:
    ms-catalog:
      address: "static://${MS_CATALOG_HOST:arka-ms-catalog}:${MS_CATALOG_GRPC_PORT:9091}"
      negotiation-type: plaintext
