# Perfil DOCKER — cuando corre dentro de Docker Compose
spring:
  kafka:
    bootstrap-servers: kafka:29092

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
