# Perfil LOCAL — desarrollo desde IntelliJ sin Docker
spring:
  kafka:
    bootstrap-servers: localhost:9092
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/db_payment
    username: arka
    password: arka
