server:
  port: "${MS_PAYMENT_PORT:8083}"

spring:
  application:
    name: ms-payment
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"

kafka:
  consumer:
    group-id: payment-service-group
    topics:
      order-events: order-events
  producer:
    topics:
      payment-events: payment-events
