server:
  port: ${MS_PAYMENT_PORT:8083}

spring:
  application:
    name: ms-payment
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  r2dbc:
    url: r2dbc:postgresql://${R2DBC_HOST:localhost}:${R2DBC_PORT:5434}/${R2DBC_DB:db_payment}
    username: ${R2DBC_USER:arka}
    password: ${R2DBC_PASSWORD:arkaSecret2025}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
