server:
  port: ${MS_SHIPPING_PORT:8088}

spring:
  application:
    name: ms-shipping
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  r2dbc:
    url: r2dbc:postgresql://${R2DBC_HOST:localhost}:${R2DBC_PORT:5436}/${R2DBC_DB:db_shipping}
    username: ${R2DBC_USER:arka}
    password: ${R2DBC_PASSWORD:arkaSecret2025}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
