# Perfil DOCKER — cuando corre dentro de Docker Compose
# Solo sobreescribe los campos que difieren del application.yaml base.
spring:
  r2dbc:
    url: r2dbc:postgresql://arka-db-shipping:5432/db_shipping
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: kafka:29092

aws:
  endpoint: http://localstack:4566
  region: us-east-1

adapters:
  aws:
    s3:
      endpoint: http://localstack:4566
      region: us-east-1
      bucket-name: arka-shipping-labels

logging:
  level:
    com.arka: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.data.r2dbc: DEBUG
