server:
  port: ${MS_NOTIFICATIONS_PORT:8085}

spring:
  application:
    name: ms-notifications
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:arka}:${MONGO_PASSWORD:arkaSecret2025}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/db_notifications?authSource=admin
