# Perfil LOCAL — desarrollo desde IntelliJ sin Docker
# Solo sobreescribe los campos que difieren del application.yaml base.
spring:
  data:
    mongodb:
      uri: mongodb://arka:arkaSecret2025@localhost:27017/db_catalog?authSource=admin&replicaSet=rs0
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.arka: DEBUG
