# Perfil DOCKER — cuando corre dentro de Docker Compose
# Solo sobreescribe los campos que difieren del application.yaml base.
# Apunta a los hostnames de los contenedores definidos en compose.yaml.

grpc:
  server:
    port: 9091  # ms-order cliente apunta a ms-catalog:9091 dentro de la red Docker

spring:
  mongodb:
    uri: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@arka-mongodb:27017/db_catalog?authSource=admin&replicaSet=rs0&uuidRepresentation=standard"
  data:
    redis:
      host: arka-redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:29092

logging:
  level:
    com.arka: DEBUG
    org.springframework.data.mongodb.core: DEBUG
    org.mongodb.driver: WARN
